### PR TITLE
added program on list in python

### PR DESCRIPTION
**Pull request by kritika2311**
This program is implementing the basic functions (adding, sorting, deleting, traversing, searching) on a list in python language.
issue no:#73

### CODE REVIEW

**Comment by kritika2311** [comment]
Please merge my PR This the same code in which you said to make changes and add in other directory so i made this pull request please consider it.

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Please update the README also.

**Comment by kritika2311** [comment]
What update are to be added in the readme please describe.

**Comment by GauravWalia19** [comment]
Under the LISTS / INBUILT LISTS / LINKED LIST / section add

 Added python link to your file

For more details refer to README.

**Comment by kritika2311** [comment]
okay I understand the changes thank you for describing.

**Comment by kritika2311** [comment]
update the readme.

**Comment by kritika2311** [comment]
updated the readme

**Comment by GauravWalia19** [comment]
Can you do the changes in this PR only instead of sending new one.

**Comment by kritika2311** [comment]
Okay I'll try to do actually I don't know much about GitHub. I am the
beginner so little confused about the things.

**Comment by kritika2311** [comment]
sorry sir at starting I have not made changes by forking it and rather i just added the new file code so now I forked the repo and made changes and push it again please review that pull request and close this one. Sorry for the inconvience.

**Pull request closed without merging**
