### PR TITLE
added program using various functions on list in python

### PR DESCRIPTION
**Pull request by kritika2311**
Program performing pre-defined functions of list in python.

### CODE REVIEW

**Comment by kritika2311** [comment]
Whatever I understand from this repository it is a data structure programming based hence I added a python list code which is not in your repository.

**Comment by GauravWalia19** [comment]
Please create a issue with HacktoberFest20 template first then we will discuss there

**Comment by kritika2311** [comment]
Okay first I will create the issue.

**Comment by kritika2311** [comment]
Added the issue please take a look.

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
Add some relevant comments so that other newbies can read the code easily.
Also update the README.

**Comment by kritika2311** [comment]
Okay I will update the readme.

**Comment by kritika2311** [comment]
I have added comments the change what u said now please merge the pull request

**Comment by kritika2311** [comment]
I have another pull request which is update with the changes you want in the pull request and program please accept that pull request and i am closing this one.

**Pull request closed without merging**
