### PR TITLE
added program on list in python

### PR DESCRIPTION
**Pull request by kritika2311**
Updated Readme.md file also.

### CODE REVIEW

**Review by GauravWalia19 — CHANGES_REQUESTED** [review]
There is issue with code you have added in python language but the code file is not in right location and the code extension is not present it means its just a text file. In earlier Pull Request it was right. Now only README.md is right in this case can you please update this one.

**Review by kritika2311 — COMMENTED** [review]
I have reviewed the files and done the changes.

**Comment by GauravWalia19** [comment]
@kritika2311 I am merging the PR this time. But try not to add your name as a code file name like **kritika2311.py** it is not a good Open Source contributing practice.

**Review by GauravWalia19 — APPROVED** [review]

**Comment by kritika2311** [comment]
Yes I will keep in mind and sorry for the wrong way of naming actually I
don't know how to name in open source code.

**Pull request merged**
